name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

permissions:
  contents: read

jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21']
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn -B package --file pom.xml

      - name: Rename jar file
        run: |
          mv target/keycloak-gsis-providers-1.0.0-SNAPSHOT.jar target/keycloak-gsis-providers-java-${{ matrix.java }}-v1.0.0-SNAPSHOT.jar

      - name: Upload jar file
        uses: actions/upload-artifact@v4
        with:
          name: keycloak-gsis-providers-java-${{ matrix.java }}
          path: target/keycloak-gsis-providers-java-${{ matrix.java }}-v1.0.0-SNAPSHOT.jar
          if-no-files-found: error
